"""update_models

Revision ID: 4f65dc190d88
Revises: 1f975536f48c
Create Date: 2026-03-19 13:12:22.135500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f65dc190d88'
down_revision: Union[str, Sequence[str], None] = '1f975536f48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    trigger_source_enum = postgresql.ENUM(
        'USER', 'SCHEDULE', 'SENSOR', 'AUTOMATION', 'PHYSICAL_ATTRIBUTED', 'PHYSICAL_UNKNOWN',
        name='triggersource'
    )
    event_type_enum = postgresql.ENUM(
        'DEVICE_ON', 'DEVICE_OFF', 'FACE_UNLOCK', 'FORGOT_OFF', 'SCENE_ON',
        name='eventtype'
    )
    trigger_source_enum.create(bind, checkfirst=True)
    event_type_enum.create(bind, checkfirst=True)

    op.create_table('user_presence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=True),
    sa.Column('detected_by', sa.String(length=20), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_presence_id'), 'user_presence', ['id'], unique=False)
    op.create_table('user_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=True),
    sa.Column('pattern_type', sa.Enum('CLUSTER', 'TIME_HABIT', 'CORRELATION', 'ANOMALY', name='patterntype'), nullable=False),
    sa.Column('pattern_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_patterns_id'), 'user_patterns', ['id'], unique=False)
    op.create_table('suggestion_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Enum('SCHEDULE', 'ALERT', 'AUTOMATION', name='actiontype'), nullable=False),
    sa.Column('suggestion_text', sa.Text(), nullable=False),
    sa.Column('suggestion_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('was_accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['user_patterns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestion_logs_id'), 'suggestion_logs', ['id'], unique=False)
    op.add_column('activity_logs', sa.Column('session_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('activity_logs', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('activity_logs', sa.Column('trigger_source', sa.Enum('USER', 'SCHEDULE', 'SENSOR', 'AUTOMATION', 'PHYSICAL_ATTRIBUTED', 'PHYSICAL_UNKNOWN', name='triggersource'), nullable=False))
    op.add_column('activity_logs', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('activity_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('activity_logs', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DEVICE_ON', 'DEVICE_OFF', 'FACE_UNLOCK', 'FORGOT_OFF', 'SCENE_ON', name='eventtype'),
               postgresql_using='event_type::eventtype',
               nullable=False)
    op.alter_column('activity_logs', 'device_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_activity_logs_timestamp'), 'activity_logs', ['timestamp'], unique=False)
    op.drop_column('activity_logs', 'event_metadata')
    op.add_column('schedules', sa.Column('source_suggestion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schedules', 'suggestion_logs', ['source_suggestion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    trigger_source_enum = postgresql.ENUM(
        'USER', 'SCHEDULE', 'SENSOR', 'AUTOMATION', 'PHYSICAL_ATTRIBUTED', 'PHYSICAL_UNKNOWN',
        name='triggersource'
    )
    event_type_enum = postgresql.ENUM(
        'DEVICE_ON', 'DEVICE_OFF', 'FACE_UNLOCK', 'FORGOT_OFF', 'SCENE_ON',
        name='eventtype'
    )

    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_column('schedules', 'source_suggestion_id')
    op.add_column('activity_logs', sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_activity_logs_timestamp'), table_name='activity_logs')
    op.alter_column('activity_logs', 'device_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('activity_logs', 'event_type',
               existing_type=sa.Enum('DEVICE_ON', 'DEVICE_OFF', 'FACE_UNLOCK', 'FORGOT_OFF', 'SCENE_ON', name='eventtype'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('activity_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('activity_logs', 'metadata')
    op.drop_column('activity_logs', 'trigger_source')
    op.drop_column('activity_logs', 'duration_seconds')
    op.drop_column('activity_logs', 'session_end')
    op.drop_index(op.f('ix_suggestion_logs_id'), table_name='suggestion_logs')
    op.drop_table('suggestion_logs')
    op.drop_index(op.f('ix_user_patterns_id'), table_name='user_patterns')
    op.drop_table('user_patterns')
    op.drop_index(op.f('ix_user_presence_id'), table_name='user_presence')
    op.drop_table('user_presence')

    trigger_source_enum.drop(bind, checkfirst=True)
    event_type_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
