"""update_models_v2

Revision ID: b30149459cec
Revises: 4f65dc190d88
Create Date: 2026-03-19 14:54:01.704400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b30149459cec'
down_revision: Union[str, Sequence[str], None] = '4f65dc190d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'MEMBER', 'GUEST', name='userrole', create_type=False), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('home_id', 'user_id', name='uq_home_user')
    )
    op.create_index(op.f('ix_home_users_id'), 'home_users', ['id'], unique=False)
    op.add_column('activity_logs', sa.Column('home_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_activity_logs_home_id'), 'activity_logs', ['home_id'], unique=False)
    op.create_foreign_key(None, 'activity_logs', 'homes', ['home_id'], ['id'])
    op.add_column('rooms', sa.Column('home_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'rooms', 'homes', ['home_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_patterns', sa.Column('home_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'user_patterns', 'homes', ['home_id'], ['id'])
    op.add_column('user_presence', sa.Column('home_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user_presence', 'homes', ['home_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_presence', type_='foreignkey')
    op.drop_column('user_presence', 'home_id')
    op.drop_constraint(None, 'user_patterns', type_='foreignkey')
    op.drop_column('user_patterns', 'home_id')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'home_id')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_index(op.f('ix_activity_logs_home_id'), table_name='activity_logs')
    op.drop_column('activity_logs', 'home_id')
    op.drop_index(op.f('ix_home_users_id'), table_name='home_users')
    op.drop_table('home_users')
    op.drop_table('homes')
    # ### end Alembic commands ###
